#!/bin/sh

TIMESTAMP=`date "+%b-%d-%Y-%T"`

# Set default configuration
#--------------------------

logger -p local6.notice -t installer "app-elastic-kibana-core - securing default configuration"

if [ -e /etc/kibana/kibana.yml ]; then
    cp /etc/kibana/kibana.yml /var/clearos/elastic_kibana/backup/kibana.yml.$TIMESTAMP
fi

cp /usr/clearos/apps/elastic_kibana/deploy/kibana.yml /etc/kibana/kibana.yml

# As suggested in kibana RPM install output
#------------------------------------------

systemctl daemon-reload >/dev/null 2>&1
systemctl disable kibana.service >/dev/null 2>&1
systemctl stop kibana.service >/dev/null 2>&1
